replace duplicated Bitmaps with an powerful already importd one
immutable/contracts pull request #211
Opened 2024-04-25 07:54 UTC by yuhuajing

The flattern files will faile because the duplicated BitMaps import, thus we strongly suggest that you could replace the imported BitMaps library in the _/contracts/token/erc721/abstract/ERC721Hybrid.sol_ with `_import {BitMaps} from "solidity-bits/contracts/BitMaps.sol";` in the _\contracts\token\erc721\erc721psi\ERC721PsiBurnable.sol_.

2024-04-26 03:44 UTC, drinkcoffee commented
@yuhuajing  we are discussing the merits of your PR. One decision we have made is that we won't include IDE specific files in the repo. As such, could you update your PR to gitignore the whole .idea directory, and remove the associated files from your PR

2024-04-26 03:48 UTC, drinkcoffee commented
A result of the change beyond flatten files possibly being easier, is that the resulting contract should be smaller. ERC721Psi calls **set** and **get** on solidity-bits version of BitMaps, where as ImmutableERC721Base uses the same functions in Open Zeppelin's code. This means that two copies of these functions will be included in the final contract bytecode. Making the change described in this PR will mean there is only one copy of the **set** and **get** functions.

2024-04-26 03:49 UTC, drinkcoffee requested changes
Please .gitignore the whole .idea directory, and remove .idea files. We have decided not to include IDE specific files in the repo.

2024-05-06 02:47 UTC, yuhuajing commented
> Please .gitignore the whole .idea directory, and remove .idea files. We have decided not to include IDE specific files in the repo.

Already done

2026-06-08 04:41 UTC, drinkcoffee commented
We now only use OpenZeppelin's BitMap. Hence, this issue no longer applies. Closing.

2026-06-08 04:41 UTC, closed without merging